version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - seijikohara
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directories:
      - /
      - /examples/webflux-jetty-java
      - /examples/webflux-tomcat-java
      - /examples/webmvc-jetty-java
      - /examples/webmvc-tomcat-java
      - /examples/webmvc-tomcat-kotlin
    schedule:
      interval: weekly
    assignees:
      - seijikohara
    labels:
      - type:dependencies
    groups:
      spring-boot:
        patterns:
          - org.springframework.boot:*
      logback-access:
        patterns:
          - ch.qos.logback.access:*
