config:
  warningsAsErrors: true
comments:
  UndocumentedPublicClass:
    active: true
    ignoreDefaultCompanionObject: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
complexity:
  TooManyFunctions:
    ignoreDeprecated: true
    ignoreInternal: true
    ignoreOverridden: true
    ignorePrivate: true
ktlint:
  BlankLineBetweenWhenConditions:
    active: false
  ClassSignature:
    active: false
  EnumWrapping:
    active: false
  FunctionExpressionBody:
    active: false
  FunctionSignature:
    active: false
  NoBlankLineBeforeRbrace:
    active: false
style:
  ClassOrdering:
    active: true
  ForbiddenComment:
    active: false
  FunctionOnlyReturningConstant:
    active: false
  NoTabs:
    active: true
  ReturnCount:
    excludeLabeled: true
    excludeGuardClauses: true
  SerialVersionUIDInSerializableClass:
    active: false
  UnusedPrivateFunction:
    allowedNames: (readObject|readObjectNoData|readResolve|writeObject|writeReplace)
