name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    env:
      GRADLE_OPTS: -Dorg.gradle.console=colored
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.1.0
      - name: Build
        run: ./gradlew clean build publishToMavenLocal
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6.0.0
        with:
          use_oidc: true
          fail_ci_if_error: true
