name: Deploy
on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        type: string
permissions:
  contents: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    env:
      MAVEN_ARGS: -B --color always
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 25
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Prepare release
        run: |
          if git rev-parse -q --verify "refs/tags/v${{ inputs.release-version }}" &>/dev/null; then
            echo "Skipping release preparation. Tag v${{ inputs.release-version }} already exists."
          else
            mvn -DreleaseVersion="${{ inputs.release-version }}" release:clean release:prepare
          fi
        if: ${{ inputs.release-version }}
      - name: Checkout release tag
        uses: actions/checkout@v6.0.2
        with:
          ref: refs/tags/v${{ inputs.release-version }}
        if: ${{ inputs.release-version }}
      - name: Deploy
        run: mvn clean deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
