name: Snapshot
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 12 * * 5
  workflow_dispatch:
jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-24.04
    env:
      MAVEN_ARGS: -B --color always
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4.2.2
      - name: Setup Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Export the project version
        run: echo PROJECT_VERSION=$(mvn -Dexpression=project.version -DforceStdout -q help:evaluate) >>$GITHUB_ENV
      - name: Snapshot the project
        run: mvn clean deploy
        if: ${{ endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
